### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChrisPontrelli** [Suprndm/gangstabit#2]
So this is essentially a program to predict what multi the crash will happen at on bustabit? has it been tested?

Thanks!

**Comment by Suprndm** [comment]
Hi ChrisPontrelli,

Mostly i tried to brute force some best strategy through mass simulating millions bets on bustabit, to see if there were any silver bullet strategy.

I Then deployed the strategy online, and lost half of my money.

Basically my algoirthm was over learning, on specific random events, and not generalizing at all any good knowledge.
I dont think there is any knowledge to learn, as bustabit is mainly a random mechanism.

**Comment by ChrisPontrelli** [comment]
Hi Suprndm,

Do you think it'll be easier to build something like this for use on Duelbits? The hashes for every round are displayed after the crash so maybe it'll provide a good starting point for the algo. Also, would it be possible to create something like this for mines or DB roulette? sorry for all the questions/hypotheticals, I'm but a mere gambler trying to beat the house same as you hahaha

Thanks,
Chris

**Comment by Suprndm** [comment]
I don't know about others games, but usually you can never beat the house on casino games because of the  "House always win principle". No matter what happens, the house always get a small share of any bets, like  5%. So the players, as a total, will always have their money drains over bets / time. 
The only possible strategy is not to beat the house, but to play better than the other players. To be among the players that win money, and not the players that loses money. That's kind of a race between all players to find the best and most efficient way to play and lose less than other. And in all games you can find the same similar race pattern. At the beginning of a new game, some quick players will make money thanks to better strategies, but eventually, the best method ( wich is mathematically determined) is being more and more known, to the point that everyone knows it. When this happens all players  play the most optimal way to play the game. You can no longer be Better than others, your chances of wining equalizes, and you all lose because of the 5% tax of the house.

Take a look at my other project on Poker, I did a more advance project on that. An AI that plays Expresso tables ( 3 players table) on Winamax poker game. I discovered the best strategy, and all players were doing the same. We all ended up with 33.33% chance win rate. But because of the House tax (5%), you actually need to have a winrate of 37% to actually make money. I also stopped this project.

A more larger reflexion would be to think from reverse. If there were a possible way to make money on the games, and beat the house, well the house would not exist. Therefor its existence prove that they is no way to beat the house.

The only way to make money, is to be the house =p

**Comment by ChrisPontrelli** [comment]
Either way, if you want to look into it, It might be worthwhile. DB Roulette/Mines are on a provably fair system so 
I have a feeling someone could crack it or predict it somehow

Thanks for the reply though! have a great day!

**Comment by ChrisPontrelli** [comment]
If you'd like to work on something like that in the future, hit me up!
